name: text_expressions
version: 2.0.0

description: >-
  A tiny and complete tool to supercharge static JSON strings
  with dynamic, user-defined expressions.

homepage: https://github.com/wordcollector/text_expressions
repository: https://github.com/wordcollector/text_expressions
issue_tracker: https://github.com/wordcollector/text_expressions/issues

environment:
  sdk: '>=2.17.0 <3.0.0'

dev_dependencies:
  test: ^1.22.2
  words: ^0.1.1
